### ISSUE TITLE
在一个仓库没有任何提交的时候，会出错，无法获取历史msg

### ISSUE THREAD

**Issue by Leizhenpeng** [ConnectAI-E/kimi-commits-intellij#16]
```

com.intellij.openapi.vcs.VcsException: bad revision 'HEAD'

Command line: [git -c credential.helper= -c core.quotepath=false -c log.showSignature=false log --name-status --pretty=format:%x01%x01%H%x02%x02%ct%x02%x02%an%x02%x02%ae%x02%x02%cn%x02%x02%ce%x02%x02%P%x02%x02%s%x02%x02%b%x02%x02%B%x02%x02%at%x03%x03 --encoding=UTF-8 HEAD --full-history --simplify-merges -- .]
	at git4idea.history.GitLogOutputSplitter.processTerminated(GitLogOutputSplitter.java:87)
	at jdk.internal.reflect.GeneratedMethodAccessor72.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:119)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:84)
	at jdk.proxy2/jdk.proxy2.$Proxy123.processTerminated(Unknown Source)
	at git4idea.commands.GitTextHandler$1.processTerminated(GitTextHandler.java:93)
	at com.intellij.execution.process.ProcessHandler$2.processTerminated(ProcessHandler.java:259)
	at com.intellij.execution.process.ProcessHandler.lambda$notifyTerminated$2(ProcessHandler.java:204)
	at com.intellij.execution.process.ProcessHandler$TasksRunner.execute(ProcessHandler.java:322)
	at com.intellij.execution.process.ProcessHandler.notifyTerminated(ProcessHandler.java:187)
	at com.intellij.execution.process.ProcessHandler.notifyProcessTerminated(ProcessHandler.java:183)
	at com.intellij.execution.process.BaseProcessHandler.onOSProcessTerminated(BaseProcessHandler.java:59)
	at com.intellij.execution.process.OSProcessHandler.onOSProcessTerminated(OSProcessHandler.java:186)
	at com.intellij.execution.process.BaseOSProcessHandler$1.lambda$startNotified$0(BaseOSProcessHandler.java:82)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$0(ProcessWaitFor.java:45)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.execution.process.ProcessWaitFor.lambda$new$1(ProcessWaitFor.java:23)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by Leizhenpeng** [comment]
11

**Comment by iswswings** [comment]
11
